# VERSION CODE
# update the flutter version code by 1
# eg 1.1.1+1 -> 1.1.1+2

lane :update_version_code do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    version_component: "version_code")
end

# if you dont specify `version_component` version_code will the default value
lane :update_version_default do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml", value: "9")
end

# set the flutter version - patch to `value` given
# eg 1.1.1+1 -> 1.1.1+100
lane :set_version_code do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    value: "100",
                    version_component: "version_code")
end
# VERSION - PATCH
# update the flutter version - patch by 1
# eg 1.1.1 -> 1.1.2

lane :update_version_patch do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    version_component: "patch")
end

# set the flutter version - patch to `value` given
# eg 1.1.1 -> 1.1.100
lane :set_version_patch do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    value: "100",
                    version_component: "patch")
end

# VERSION - MINOR
# update the flutter version - minor by 1  (also reset patch to 0)
# eg 1.1.1 -> 1.2.0
lane :update_version_minor do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    version_component: "minor")
end

# set the flutter version - major to `value` given  (also reset patch to 0)
# eg 1.1.1 -> 1.100.0
lane :set_version_minor do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    value: "100",
                    version_component: "minor")
end

# VERSION - MAJOR
# update the flutter version - major by 1 (also reset minor and patch)
# eg 1.1.1 -> 2.0.0
lane :update_version_major do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    version_component: "major")
end

# set the flutter version - major to `value` given (also reset minor and patch)
# eg 1.1.1 -> 100.0.0
lane :set_version_major do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    value: "100",
                    version_component: "major")
end

# Error
lane :invalid_version_component do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    version_component: "invalid_version_component")
end

# VERSION NAME
# update the flutter version name to `value`
# eg 1.1.1+1 -> 2.3.4+1

lane :set_verion_name do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    value: "2.3.4",
                    version_component: "version_name")
end

# VERSION
# update the flutter version to `value`
# eg 1.1.1+1 -> 2.3.4+5

lane :set_version do
  flutter_versioner(pubspec_file_path: "./example/pubspec.yaml",
                    value: "2.3.4+5",
                    version_component: "version")
end
